language: elixir
matrix:
  include:
    - otp_release: 19.2
      elixir: 1.4.2
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 17.5
    - otp_release: R16B03-1
branches:
    only:
        - master
        - travis_test
cache:
    directories:
        - $HOME/.cache/rebar3
        - priv/node_modules
install:
    - ./rebar3 deps
    - nvm install 6.2 && nvm use 6.2
    - make bootstrap_front_end
script:
    - make test
    - make test_front_end
after_success:
    - ./rebar3 cover
    - if [ $TRAVIS_OTP_RELEASE = "18.3" ]; then ./rebar3 coveralls send; fi
